version: '3.1'

services:
  # containers
  database:
    image: mysql:5.7
    restart: always
    container_name: mysql_compose
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./backend/database/mysql-seeder:/docker-entrypoint-initdb.d

  api:
    build: ./backend
    container_name: backend_compose
    ports:
      - 3333:3333
    depends_on:
      - database
    volumes:
      - /app/node_modules
      - ./backend:/app

  web:
    build: ./frontend
    container_name: frontend_compose
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - api
